# -*- coding: utf-8 -*-
"""Agentic_AI_Travel_Planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1vcA7HeWDBxkxnEZBdd5UZBRJK1tEKL
"""

# STEP 1: Required Libraries Install
!pip install langchain langchain-community langchain-openai openai requests

!pip install requests==2.32.4

# STEP 2: Import Libraries (Safe Imports)
import json
import requests
from typing import List, Dict

# STEP 3: Upload JSON Files to Colab
from google.colab import drive
drive.mount('/content/drive')

# loading data set
BASE_PATH = "/content/drive/MyDrive/Agentic_AI_Travel_Planner"

FLIGHTS_FILE = BASE_PATH + "/content/drive/MyDrive/Agentic_AI_Travel_Planner/flights.json"
HOTELS_FILE = BASE_PATH + "/content/drive/MyDrive/Agentic_AI_Travel_Planner/hotels.json"
PLACES_FILE = BASE_PATH + "/content/drive/MyDrive/Agentic_AI_Travel_Planner/places.json"

print(FLIGHTS_FILE)

import os

data_path = "/content/drive/MyDrive/Agentic_AI_Travel_Planner"
os.listdir(data_path)

# STEP 3C: Drive se JSON Load
import json

def load_json_from_drive(file_name):
    try:
        with open(f"{data_path}/{file_name}", "r") as f:
            return json.load(f)
    except Exception as e:
        print(f" Error loading {file_name}:", e)
        return []

flights_data = load_json_from_drive("flights.json")
hotels_data  = load_json_from_drive("hotels.json")
places_data  = load_json_from_drive("places.json")

print("Flights:", len(flights_data))
print("Hotels :", len(hotels_data))
print("Places :", len(places_data))

# STEP 3D: Data Structure Verify
flights_data[0]

# hotel sample
hotels_data[0]

# Place sample
places_data[0]

# STEP 4 (UPDATED): Hotel Recommendation Tool (FIXED)
def recommend_hotel(city):
    city_hotels = [
        h for h in hotels_data
        if h["city"].lower() == city.lower()
    ]

    if not city_hotels:
        return None

    # Highest stars first, then lowest price
    best_hotel = sorted(
        city_hotels,
        key=lambda x: (-x["stars"], x["price_per_night"])
    )[0]

    return best_hotel

hotel = recommend_hotel("Delhi")
hotel

# STEP 5 (UPDATED): Places Recommendation Tool (FIXED)
def recommend_places(city, limit=3):
    city_places = [
        p for p in places_data
        if p["city"].lower() == city.lower()
    ]

    # Highest rating first
    city_places = sorted(
        city_places,
        key=lambda x: x["rating"],
        reverse=True
    )

    return city_places[:limit]

places = recommend_places("Delhi")

for p in places:
    print(p["name"], "-", p["rating"])

# STEP 6: Budget Function (HOTEL FIX)
def calculate_budget(flight, hotel, days):
    flight_cost = flight["price"]
    hotel_cost = hotel["price_per_night"] * days
    food_local = 800 * days

    total = flight_cost + hotel_cost + food_local

    return {
        "flight": flight_cost,
        "hotel": hotel_cost,
        "food_travel": food_local,
        "total": total
    }

# STEP 7A: LangChain Imports
from langchain.tools import tool

# STEP 7B: Flight Search Tool (LangChain Tool)
@tool
def flight_search_tool(source: str, destination: str) -> dict:
    """
    Find cheapest flight between two cities (case & space safe).
    """
    source = source.strip().lower()
    destination = destination.strip().lower()

    matches = []

    for f in flights_data:
        from_city = str(f.get("from_city", "")).strip().lower()
        to_city   = str(f.get("to_city", "")).strip().lower()

        if source in from_city and destination in to_city:
            matches.append(f)

    if not matches:
        return {
            "error": "No flights found",
            "available_from_cities": list(set(f.get("from_city") for f in flights_data[:10])),
            "available_to_cities": list(set(f.get("to_city") for f in flights_data[:10]))
        }

    cheapest = min(matches, key=lambda x: x["price"])
    return cheapest

flight_search_tool.run({"source": "Delhi", "destination": "Goa"})

flights_data[0]

for f in flights_data[:5]:
    print(f)

# First flight record ka full structure
flights_data[0].keys()

flights_data[0]

# STEP 8: FLIGHT TOOL — FINAL & PERMANENT FIX
from langchain.tools import tool

@tool
def flight_search_tool(source: str, destination: str) -> dict:
    """
    Find cheapest flight between two cities using flights.json.
    """
    source = source.strip().lower()
    destination = destination.strip().lower()

    matches = [
        f for f in flights_data
        if str(f.get("from", "")).strip().lower() == source
        and str(f.get("to", "")).strip().lower() == destination
    ]

    if not matches:
        return {
            "error": "No flights found",
            "hint": "Check source/destination spelling in flights.json"
        }

    cheapest = min(matches, key=lambda x: x["price"])
    return cheapest

# STEP 9: TEST (IMPORTANT)
flight_search_tool.run({
    "source": "Hyderabad",
    "destination": "Delhi"
})

# Hotel Tool ko RE-DEFINE
from langchain.tools import tool

@tool
def hotel_recommendation_tool(city: str) -> dict:
    """
    Recommend best hotel based on stars and price.
    """
    city_hotels = [
        h for h in hotels_data
        if h["city"].lower() == city.lower()
    ]

    if not city_hotels:
        return {"error": "No hotels found"}

    best_hotel = sorted(
        city_hotels,
        key=lambda x: (-x["stars"], x["price_per_night"])
    )[0]

    return best_hotel

@tool
def places_discovery_tool(city: str, days: int = 3) -> list:
    """
    Recommend top places based on rating.
    """
    city_places = [
        p for p in places_data
        if p["city"].lower() == city.lower()
    ]

    city_places = sorted(
        city_places,
        key=lambda x: x["rating"],
        reverse=True
    )

    return city_places[:days]

# Places Tool bhi CONFIRM
places_discovery_tool

@tool
def weather_tool(latitude: float, longitude: float) -> list:
    """
    Get 3-day weather forecast (max temperature).
    """
    url = f"https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&daily=temperature_2m_max&timezone=auto"
    response = requests.get(url)

    if response.status_code != 200:
        return ["Weather data unavailable"]

    data = response.json()
    return data["daily"]["temperature_2m_max"][:3]

# Weather Tool CONFIRM
weather_tool

# Tools List
tools = [
    flight_search_tool,
    hotel_recommendation_tool,
    places_discovery_tool,
    weather_tool
]

tools

# STEP 10: ALL TOOLS KO EK LIST ME BIND
tools = [
    flight_search_tool,
    hotel_recommendation_tool,
    places_discovery_tool,
    weather_tool
]

tools

# OpenAI API KEY SET KARO (SECURE WAY)
import os
os.environ["OPENAI_API_KEY"] = "PASTE_YOUR_OPENAI_KEY_HERE"

# City → Latitude Mapping
CITY_COORDS = {
    "delhi": (28.6139, 77.2090),
    "hyderabad": (17.3850, 78.4867),
    "goa": (15.2993, 74.1240)
}

# Agentic Planner Function
def agentic_travel_planner(source, destination, days):
    print(f"\n🧳 Planning {days}-Day Trip: {source} → {destination}\n")

    # 1️⃣ Flight
    flight = flight_search_tool.run({
        "source": source,
        "destination": destination
    })

    if "error" in flight:
        print("❌ Flight Error:", flight["error"])
        return

    # 2️⃣ Hotel
    hotel = hotel_recommendation_tool.run({
        "city": destination
    })

    if "error" in hotel:
        print("❌ Hotel Error:", hotel["error"])
        return

    # 3️⃣ Places
    places = places_discovery_tool.run({
        "city": destination,
        "days": days
    })

    # 4️⃣ Weather
    lat, lon = CITY_COORDS.get(destination.lower(), (None, None))
    weather = weather_tool.run({
        "latitude": lat,
        "longitude": lon
    })

    # 5️⃣ Budget
    total_budget = (
        flight["price"] +
        hotel["price_per_night"] * days +
        800 * days
    )

    # 🔥 FINAL OUTPUT
    print("✈️ Flight Selected:")
    print(f"  {flight['airline']} | ₹{flight['price']}")

    print("\n🏨 Hotel Selected:")
    print(f"  {hotel['name']} | ⭐{hotel['stars']} | ₹{hotel['price_per_night']}/night")

    print("\n📍 Itinerary:")
    for i, p in enumerate(places, 1):
        print(f"  Day {i}: {p['name']}")

    print("\n🌦 Weather (Max Temp):", weather)
    print("\n💰 Estimated Budget: ₹", total_budget)

# RUN THE AGENT (FINAL DEMO)
agentic_travel_planner(
    source="Hyderabad",
    destination="Delhi",
    days=2
)

# FINAL OUTPUT KO JSON FORMAT
def agentic_travel_planner_json(source, destination, days):
    flight = flight_search_tool.run({"source": source, "destination": destination})
    hotel = hotel_recommendation_tool.run({"city": destination})
    places = places_discovery_tool.run({"city": destination, "days": days})
    lat, lon = CITY_COORDS.get(destination.lower(), (None, None))
    weather = weather_tool.run({"latitude": lat, "longitude": lon})

    budget = {
        "flight": flight["price"],
        "hotel": hotel["price_per_night"] * days,
        "food_travel": 800 * days,
        "total": flight["price"] + hotel["price_per_night"] * days + 800 * days
    }

    return {
        "trip_summary": {
            "source": source,
            "destination": destination,
            "days": days
        },
        "flight": flight,
        "hotel": hotel,
        "itinerary": places,
        "weather": weather,
        "budget": budget
    }

agentic_travel_planner_json("Hyderabad", "Delhi", 2)

!pip install streamlit
!pip install pyngrok

import streamlit as st
print("Streamlit Installed")

from pyngrok import ngrok
ngrok.set_auth_token("34pBZArucIzwiqZA2y1JZjVBDBj_2o3vCZUEdbHzeuW5h9nfi")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(page_title="Agentic AI Travel Planner", layout="centered")
# 
# st.title("✈️ Agentic AI Travel Planner")
# st.caption("Agentic AI-Based Travel Planning System")
# 
# # =====================
# # BASIC TRIP INPUT
# # =====================
# source = st.text_input("Source City", "Hyderabad")
# destination = st.text_input("Destination City", "Delhi")
# days = st.slider("Trip Duration (Days)", 1, 7, 2)
# 
# st.divider()
# 
# # =====================
# # FLIGHT OPTIONS
# # =====================
# st.subheader("🛫 Flight Preferences")
# 
# flight_id = st.text_input("Flight ID", "FL0001")
# airline = st.selectbox("Airline", ["IndiGo", "Air India", "Vistara"])
# travel_class = st.selectbox("Class", ["Economy", "Business"])
# stops = st.selectbox("Stops", [0, 1, 2])
# refundable = st.checkbox("Refundable Ticket")
# meal = st.checkbox("Meal Included")
# 
# st.divider()
# 
# # =====================
# # HOTEL OPTIONS
# # =====================
# st.subheader("🏨 Hotel Preferences")
# 
# hotel_name = st.selectbox(
#     "Hotel Name",
#     ["Comfort Suites", "Grand Palace Hotel"]
# )
# stars = st.selectbox("Hotel Stars", [3, 4, 5])
# price_per_night = st.number_input(
#     "Price per Night (₹)",
#     min_value=1000,
#     value=3500
# )
# 
# amenities = st.multiselect(
#     "Amenities",
#     ["wifi", "breakfast", "gym", "pool", "parking"],
#     default=["wifi", "breakfast"]
# )
# 
# st.divider()
# 
# # =====================
# # PLACES OPTIONS
# # =====================
# st.subheader("📍 Places to Visit")
# 
# places = st.multiselect(
#     "Select Places",
#     ["Famous Fort", "Popular Museum", "City Market", "Heritage Palace"],
#     default=["Famous Fort", "Popular Museum"]
# )
# 
# st.divider()
# 
# # =====================
# # PLAN TRIP
# # =====================
# if st.button("Plan Trip"):
#     st.success("Trip Planned Successfully ✅")
# 
#     # Flight Data
#     st.subheader("✈️ Flight Details")
#     flight_data = {
#         "flight_id": flight_id,
#         "airline": airline,
#         "from": source,
#         "to": destination,
#         "class": travel_class,
#         "stops": stops,
#         "refundable": refundable,
#         "meal": meal,
#         "price": 2907
#     }
#     st.json(flight_data)
# 
#     # Hotel Data
#     st.subheader("🏨 Hotel Details")
#     hotel_data = {
#         "name": hotel_name,
#         "stars": stars,
#         "price_per_night": price_per_night,
#         "amenities": amenities
#     }
#     st.json(hotel_data)
# 
#     # Itinerary
#     st.subheader("📅 Day-wise Itinerary")
#     for i, place in enumerate(places, start=1):
#         st.write(f"Day {i}: {place}")
# 
#     # Budget
#     st.subheader("💰 Budget Breakdown")
#     hotel_cost = price_per_night * days
#     total_budget = 2907 + hotel_cost
# 
#     budget = {
#         "flight_cost": 2907,
#         "hotel_cost": hotel_cost,
#         "total_estimated_budget": total_budget
#     }
#     st.json(budget)
#

from pyngrok import ngrok
!streamlit run app.py &>/content/logs.txt &
public_url = ngrok.connect(8501)
public_url